FROM ubuntu:22.04 as model_create
USER root
ENV DEBIAN_FRONTEND=noninteractive
ARG BUILD_DEPENDENCIES="vim git wget python3-pip"
RUN apt -y update && \
    apt install -y ${BUILD_DEPENDENCIES} && \
    rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
RUN apt -y update && apt install -y wget && \
    rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN git clone https://github.com/openvinotoolkit/model_server; cd model_server/demos/common/export_models; 

WORKDIR model_server/demos/common/export_models

RUN cd ../export_models; pip3 install -r requirements.txt
RUN mkdir -p models; python3 export_model.py embeddings --source_model BAAI/bge-small-en --weight-format int8 --config_file_path models/config_all.json --model_repository_path models 
RUN python3 export_model.py embeddings --source_model sentence-transformers/all-mpnet-base-v2 --weight-format int8 --config_file_path models/config_all.json --model_repository_path models
#python export_model.py embeddings --source_model Alibaba-NLP/gte-large-en-v1.5 --weight-format int8 --config_file_path models/config_all.json

FROM openvino/model_server:latest-gpu
COPY --from=model_create model_server/demos/common/export_models .
RUN echo "---Embedding Models available in image--- "; cat models/config_all.json; sleep 5
